//! Architectural comparison against observations generated by this CI run.
use paludarium_cpu::{CpuState, step};
use paludarium_mmu::{AddressSpace, MappingKind, Prot};
use paludarium_types::{ExitReason, GuestAddr};
#[path = "../../../../tests/guests/u3/native-contract.rs"]
mod native_contract;

fn bytes(text: &str) -> Vec<u8> {
    assert!(text.len().is_multiple_of(2));
    (0..text.len())
        .step_by(2)
        .map(|n| u8::from_str_radix(&text[n..n + 2], 16).unwrap())
        .collect()
}

pub fn compare(text: &str, fault_rows: bool) -> usize {
    compare_profile(text, fault_rows, None)
}

pub fn compare_profile(text: &str, fault_rows: bool, cpuid: Option<&str>) -> usize {
    let amd = if fault_rows {
        native_contract::amd_profile(cpuid.expect("fresh native CPU profile required"))
    } else {
        false
    };
    let mut differences = std::collections::BTreeSet::new();
    let mut count = 0;
    for row in text.lines().filter(|row| !row.is_empty()) {
        let f: Vec<_> = row.split('|').collect();
        assert_eq!(f.len(), if fault_rows { 13 } else { 7 });
        let (code, input, before, expected, after) = if fault_rows {
            (
                bytes(f[8]),
                bytes(f[9]),
                bytes(f[10]),
                bytes(f[11]),
                bytes(f[12]),
            )
        } else {
            let input = bytes(f[4]);
            (bytes(f[3]), input.clone(), input, bytes(f[5]), bytes(f[6]))
        };
        assert_eq!(input.len(), 512);
        assert_eq!(expected.len(), 280);
        let scenario = if fault_rows {
            f[1].parse::<u32>().unwrap()
        } else {
            10
        };
        let offset = match scenario {
            2 => 4096 - 24,
            3 => 1,
            _ => 0,
        };
        let address = GuestAddr(0x40000 + offset);
        let mut memory = AddressSpace::new();
        memory
            .map(
                Some(GuestAddr(0x10000)),
                4096,
                Prot::READ_WRITE,
                MappingKind::Anonymous,
            )
            .unwrap();
        memory.write(GuestAddr(0x10000), &code).unwrap();
        memory
            .protect(GuestAddr(0x10000), 4096, Prot::READ_EXEC)
            .unwrap();
        memory
            .map(
                Some(GuestAddr(0x40000)),
                8192,
                Prot::READ_WRITE,
                MappingKind::Anonymous,
            )
            .unwrap();
        memory.write(address, &before).unwrap();
        match scenario {
            0 => memory
                .protect(GuestAddr(0x40000), 8192, Prot::NONE)
                .unwrap(),
            1 => memory
                .protect(GuestAddr(0x40000), 8192, Prot::READ)
                .unwrap(),
            2 => memory
                .protect(GuestAddr(0x41000), 4096, Prot::NONE)
                .unwrap(),
            _ => (),
        }
        let mut state = CpuState::new(GuestAddr(0x10000), GuestAddr(0x80000));
        for n in 0..16 {
            state.xmm[n] = u128::from_le_bytes(input[n * 16..n * 16 + 16].try_into().unwrap());
        }
        state.mxcsr = u32::from_le_bytes(input[256..260].try_into().unwrap());
        state.gpr[0] = 0x8000_0001_7fff_0011;
        state.gpr[2] = address.0;
        state.rflags = 0x8d7;
        let original = state.clone();
        let result = step(&mut state, &memory);
        if fault_rows && native_contract::amd_sha_difference(&f, amd) {
            assert!(
                differences.insert((f[0], scenario)),
                "duplicate AMD SHA disposition"
            );
            assert_eq!(
                result,
                Err(ExitReason::GeneralProtection { rip: original.rip })
            );
            assert_eq!(state.gpr, original.gpr);
            assert_eq!(state.xmm, original.xmm);
            assert_eq!(state.rip, original.rip);
            assert_eq!(state.mxcsr, original.mxcsr);
            assert_eq!(state.rflags, original.rflags);
            memory
                .protect(GuestAddr(0x40000), 8192, Prot::READ_WRITE)
                .unwrap();
            let mut observed = [0; 512];
            memory.read(address, &mut observed).unwrap();
            assert_eq!(observed.as_slice(), before);
            println!(
                "explicit virtual Intel alignment contract: {} scenario{}; observed AMD native identity differs",
                f[0], scenario
            );
            count += 1;
            continue;
        }
        if fault_rows {
            let signal = f[2].parse::<u32>().unwrap();
            let trap = f[5].parse::<u32>().unwrap();
            match (signal, trap, result) {
                (0, 0, Ok(())) => assert_eq!(state.rip, GuestAddr(0x10000 + code.len() as u64)),
                (11, 13, Err(ExitReason::GeneralProtection { rip })) => {
                    assert_eq!(rip, GuestAddr(0x10000))
                }
                (
                    11,
                    14,
                    Err(ExitReason::PageFault {
                        rip, addr, write, ..
                    }),
                ) => {
                    assert_eq!(rip, GuestAddr(0x10000));
                    assert_eq!(
                        addr.0.wrapping_sub(address.0) as i64,
                        f[7].parse::<i64>().unwrap(),
                        "{} fault address",
                        f[0]
                    );
                    assert_eq!(write, f[6].parse::<u32>().unwrap() & 2 != 0);
                }
                (8, 19, Err(ExitReason::FloatingPointFault { rip, code })) => {
                    assert_eq!(rip, GuestAddr(0x10000));
                    assert_eq!(u32::from(code), f[4].parse::<u32>().unwrap());
                }
                other => panic!("{} scenario{} exit mismatch {:?}", f[0], scenario, other),
            }
        } else {
            result.unwrap();
            assert_eq!(state.rip, GuestAddr(0x10000 + code.len() as u64));
        }
        for n in 0..16 {
            assert_eq!(
                state.xmm[n].to_le_bytes(),
                expected[n * 16..n * 16 + 16],
                "{} scenario{} XMM{}",
                f[0],
                scenario,
                n
            );
        }
        assert_eq!(
            state.gpr[0].to_le_bytes(),
            expected[256..264],
            "{} RAX",
            f[0]
        );
        // Arithmetic status, DF and OF are defined. Native trap RF is excluded.
        assert_eq!(
            state.rflags & 0xcd5,
            u64::from_le_bytes(expected[264..272].try_into().unwrap()) & 0xcd5,
            "{} flags",
            f[0]
        );
        assert_eq!(
            state.mxcsr.to_le_bytes(),
            expected[272..276],
            "{} MXCSR",
            f[0]
        );
        memory
            .protect(GuestAddr(0x40000), 8192, Prot::READ_WRITE)
            .unwrap();
        let mut observed = [0; 512];
        memory.read(address, &mut observed).unwrap();
        assert_eq!(observed.as_slice(), after, "{} memory", f[0]);
        count += 1;
    }
    assert!(count > 0, "zero differential cases");
    if fault_rows && amd {
        assert_eq!(differences.len(), 6, "exact six SHA dispositions required");
    }
    count
}
