[package]
name = "paludarium-cpu"
description = "x86-64 interpreter for paludarium"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
paludarium-types.workspace = true
paludarium-decoder.workspace = true
paludarium-mmu.workspace = true

[lints]
workspace = true
