/* Native observations only: expectations are regenerated by each test run. */
#define _GNU_SOURCE
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <sys/mman.h>
#include <ucontext.h>
#include <unistd.h>
static const uintptr_t source = 0x40000000, destination = 0x50000000;
static uintptr_t fault_instruction;
static int divide_mode;
static int pop_mode;
static int atomic_mode;
static int enter_mode;
static void fault(int signal, siginfo_t *info, void *context) {
    ucontext_t *u = context;
    char out[256];
    int raw = snprintf(out, sizeof(out), "raw_flags=%llx compare_mask=cd5 excluded_mask=~cd5\n",
        (unsigned long long)u->uc_mcontext.gregs[REG_EFL]);
    if (raw > 0 && raw < (int)sizeof(out)) write(2, out, (size_t)raw);
    if(enter_mode){
        int n=snprintf(out,sizeof(out),"signal=%d rip_delta=%lld rsp=%lld rbp=%lld flags=%llx addr=%llx m0=%llx m1=%llx\n",
          signal,(long long)(u->uc_mcontext.gregs[REG_RIP]-fault_instruction),
          (long long)(u->uc_mcontext.gregs[REG_RSP]-source),(long long)(u->uc_mcontext.gregs[REG_RBP]-source),
          (unsigned long long)(u->uc_mcontext.gregs[REG_EFL]&0xcd5),(unsigned long long)(uintptr_t)info->si_addr,
          (unsigned long long)*(uint64_t *)(source+4088),(unsigned long long)*(uint64_t *)(source+4080));
        if(n>0&&n<(int)sizeof(out))write(1,out,(size_t)n);_exit(0);
    }
    if(atomic_mode){
        int n=snprintf(out,sizeof(out),"signal=%d rip_delta=%lld rax=%llx rdx=%llx flags=%llx addr=%llx\n",
          signal,(long long)(u->uc_mcontext.gregs[REG_RIP]-fault_instruction),
          (unsigned long long)u->uc_mcontext.gregs[REG_RAX],(unsigned long long)u->uc_mcontext.gregs[REG_RDX],
          (unsigned long long)(u->uc_mcontext.gregs[REG_EFL]&0xcd5),(unsigned long long)(uintptr_t)info->si_addr);
        if(n>0&&n<(int)sizeof(out))write(1,out,(size_t)n);_exit(0);
    }
    if (pop_mode) {
        int n = snprintf(out, sizeof(out), "signal=%d rip_delta=%lld rsp=%lld flags=%llx\n",
            signal, (long long)(u->uc_mcontext.gregs[REG_RIP] - fault_instruction),
            (long long)(u->uc_mcontext.gregs[REG_RSP] - source),
            (unsigned long long)(u->uc_mcontext.gregs[REG_EFL] & 0xcd5));
        if (n > 0 && n < (int)sizeof(out)) write(1, out, (size_t)n);
        _exit(0);
    }
    if (divide_mode) {
        int n = snprintf(out, sizeof(out), "signal=%d rip_delta=%lld rax=%llx rdx=%llx flags=%llx\n",
            signal, (long long)(u->uc_mcontext.gregs[REG_RIP] - fault_instruction),
            (unsigned long long)u->uc_mcontext.gregs[REG_RAX],
            (unsigned long long)u->uc_mcontext.gregs[REG_RDX],
            (unsigned long long)(u->uc_mcontext.gregs[REG_EFL] & 0xcd5));
        if (n > 0 && n < (int)sizeof(out)) write(1, out, (size_t)n);
        _exit(0);
    }
    int n = snprintf(out, sizeof(out), "signal=%d rip_delta=%lld count=%lld src=%lld dst=%lld flags=%llx addr=%llx\n",
        signal, (long long)(u->uc_mcontext.gregs[REG_RIP] - fault_instruction),
        (long long)u->uc_mcontext.gregs[REG_RCX],
        (long long)(u->uc_mcontext.gregs[REG_RSI] - source),
        (long long)(u->uc_mcontext.gregs[REG_RDI] - destination),
        (unsigned long long)(u->uc_mcontext.gregs[REG_EFL] & 0xcd5),
        (unsigned long long)(uintptr_t)info->si_addr);
    if (n > 0 && n < (int)sizeof(out)) write(1, out, (size_t)n);
    _exit(0);
}
static int repetition(const char *scenario) {
    int scas = !strncmp(scenario,"scas",4);
    struct sigaction sa = {0};
    sa.sa_sigaction = fault; sa.sa_flags = SA_SIGINFO;
    sigemptyset(&sa.sa_mask);
    if (sigaction(SIGSEGV, &sa, NULL)) return 2;
    size_t completed = strstr(scenario,"start") ? 0 : strstr(scenario,"budget") ? 4096 : 17;
    if (mmap((void *)source, 4096, PROT_READ|PROT_WRITE,
             MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED_NOREPLACE, -1, 0) == MAP_FAILED) return 3;
    size_t destination_size=scas?4096:8192;
    if (mmap((void *)destination, destination_size, PROT_READ|PROT_WRITE,
             MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED_NOREPLACE, -1, 0) == MAP_FAILED) return 4;
    memset((void *)source, 0x31, 4096); memset((void *)destination, 0x31, destination_size);
    uintptr_t a = source + 4096 - completed, b = destination + 4096 - completed;
    size_t count = completed + 1;
    unsigned long flags = 0x8d7;
    if(scas){
        uint64_t acc=0x32;
        __asm__ volatile("leaq 1f(%%rip),%0":"=r"(fault_instruction));
        __asm__ volatile("pushq %4; popfq; 1: repne scasb"
          : "+S"(a),"+D"(b),"+c"(count),"+a"(acc):"r"(flags):"cc","memory");
        return 5;
    }
    __asm__ volatile("leaq 1f(%%rip),%0" : "=r"(fault_instruction));
    __asm__ volatile("pushq %3; popfq; 1: repe cmpsb"
                     : "+S"(a), "+D"(b), "+c"(count) : "r"(flags) : "cc", "memory");
    return 5; /* Expected fault did not occur. */
}
static int division(const char *scenario) {
    struct sigaction sa = {0};
    sa.sa_sigaction = fault; sa.sa_flags = SA_SIGINFO;
    sigemptyset(&sa.sa_mask);
    if (sigaction(SIGFPE, &sa, NULL)) return 2;
    divide_mode = 1;
    int signed_divide = !strncmp(scenario, "idiv", 4);
    int overflow = strstr(scenario, "overflow") != NULL;
    uint64_t a = overflow ? (signed_divide ? UINT64_C(0x8000000000000000) : 0) : 123;
    uint64_t d = overflow ? (signed_divide ? UINT64_MAX : 1) : 0;
    uint64_t b = overflow ? (signed_divide ? UINT64_MAX : 1) : 0;
    uint64_t flags = 0x8d7;
    if (signed_divide) {
        __asm__ volatile("leaq 1f(%%rip),%0" : "=r"(fault_instruction));
        __asm__ volatile("pushq %3; popfq; 1: idivq %%rbx" : "+a"(a), "+d"(d) : "b"(b), "r"(flags) : "cc");
    } else {
        __asm__ volatile("leaq 1f(%%rip),%0" : "=r"(fault_instruction));
        __asm__ volatile("pushq %3; popfq; 1: divq %%rbx" : "+a"(a), "+d"(d) : "b"(b), "r"(flags) : "cc");
    }
    return 5;
}
static int pop_fault(void) {
    static unsigned char alternative[65536];
    stack_t stack={.ss_sp=alternative,.ss_size=sizeof(alternative)};
    if(sigaltstack(&stack,NULL)) return 2;
    struct sigaction sa={0};sa.sa_sigaction=fault;sa.sa_flags=SA_SIGINFO|SA_ONSTACK;
    sigemptyset(&sa.sa_mask);if(sigaction(SIGSEGV,&sa,NULL))return 3;
    if(mmap((void *)source,4096,PROT_READ|PROT_WRITE,
        MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED_NOREPLACE,-1,0)==MAP_FAILED)return 4;
    *(uint64_t *)(source+4088)=123;pop_mode=1;
    uintptr_t rsp=source+4088, dst=destination;uint64_t flags=0x8d7;
    __asm__ volatile("leaq 1f(%%rip),%0":"=r"(fault_instruction));
    __asm__ volatile("movq %%rsp,%%r10; movq %0,%%rsp; pushq %2; popfq; 1: popq (%1); movq %%r10,%%rsp"
        ::"r"(rsp),"r"(dst),"r"(flags):"r10","cc","memory");
    return 5;
}
static int atomic_fault(const char *scenario){
    struct sigaction sa={0};sa.sa_sigaction=fault;sa.sa_flags=SA_SIGINFO;
    sigemptyset(&sa.sa_mask);if(sigaction(SIGSEGV,&sa,NULL))return 2;
    if(mmap((void *)source,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED_NOREPLACE,-1,0)==MAP_FAILED)return 3;
    int segmented=strstr(scenario,"gs")!=NULL;
    if(segmented&&mmap((void *)0x30000000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED_NOREPLACE,-1,0)==MAP_FAILED)return 6;
    if(segmented)*(uint64_t *)0x30000000=7;
    atomic_mode=1;uint64_t a=0,d=0,b=9,c=10,flags=0x8d7;
    if(strstr(scenario,"misaligned")){
        uintptr_t address=source+1;
        if(segmented){
            if(syscall(158,0x1001,address-0x30000000))return 7;
            address=0x30000000;
            __asm__ volatile("leaq 1f(%%rip),%0":"=r"(fault_instruction));
            __asm__ volatile("pushq %5; popfq; 1: lock cmpxchg16b %%gs:(%4)"
             :"+a"(a),"+d"(d):"b"(b),"c"(c),"r"(address),"r"(flags):"cc","memory");
            return 5;
        }
        __asm__ volatile("leaq 1f(%%rip),%0":"=r"(fault_instruction));
        __asm__ volatile("pushq %5; popfq; 1: lock cmpxchg16b (%4)"
         :"+a"(a),"+d"(d):"b"(b),"c"(c),"r"(address),"r"(flags):"cc","memory");
    }else{
        uintptr_t address=strstr(scenario,"cross")?source+4093:source;
        *(uint64_t *)address=7;
        if(mprotect((void *)(strstr(scenario,"cross")?source+4096:source),4096,PROT_READ))return 4;
        if(segmented){
            if(syscall(158,0x1001,address-0x30000000))return 7;
            address=0x30000000;
            __asm__ volatile("leaq 1f(%%rip),%0":"=r"(fault_instruction));
            __asm__ volatile("pushq %3; popfq; 1: lock cmpxchgq %2,%%gs:(%1)"
              :"+a"(a):"r"(address),"r"(b),"r"(flags),"d"(d):"cc","memory");
            return 5;
        }
        __asm__ volatile("leaq 1f(%%rip),%0":"=r"(fault_instruction));
        __asm__ volatile("pushq %3; popfq; 1: lock cmpxchgq %2,(%1)"
          :"+a"(a):"r"(address),"r"(b),"r"(flags),"d"(d):"cc","memory");
    }
    return 5;
}
static int enter_fault(const char *scenario){
    static unsigned char alternative[65536];
    stack_t stack={.ss_sp=alternative,.ss_size=sizeof(alternative)};
    if(sigaltstack(&stack,NULL))return 2;
    struct sigaction sa={0};sa.sa_sigaction=fault;sa.sa_flags=SA_SIGINFO|SA_ONSTACK;
    sigemptyset(&sa.sa_mask);if(sigaction(SIGSEGV,&sa,NULL))return 3;
    if(mmap((void *)source,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED_NOREPLACE,-1,0)==MAP_FAILED)return 4;
    for(int i=0;i<512;i++)((uint64_t *)source)[i]=42;
    enter_mode=1;uint64_t flags=0x8d7;uintptr_t rsp=source+4096,bp=source+8;
    if(!strcmp(scenario,"enter-word")){
      __asm__ volatile("leaq 1f(%%rip),%0":"=r"(fault_instruction));
      __asm__ volatile("movq %0,%%rsp; movq %1,%%rbp; pushq %2; popfq; 1: enterw $24,$6"::"r"(rsp),"r"(bp),"r"(flags):"cc","memory");
    }else if(!strcmp(scenario,"enter-allocation")){
      __asm__ volatile("leaq 1f(%%rip),%0":"=r"(fault_instruction));
      __asm__ volatile("movq %0,%%rsp; movq %1,%%rbp; pushq %2; popfq; 1: enter $8192,$0"::"r"(rsp),"r"(bp),"r"(flags):"cc","memory");
    }else{
      __asm__ volatile("leaq 1f(%%rip),%0":"=r"(fault_instruction));
      __asm__ volatile("movq %0,%%rsp; movq %1,%%rbp; pushq %2; popfq; 1: enter $24,$3"::"r"(rsp),"r"(bp),"r"(flags):"cc","memory");
    }
    _exit(5);
}
int main(int argc, char **argv) {
    if(argc==2&&!strncmp(argv[1],"enter",5))return enter_fault(argv[1]);
    if(argc==2&&!strncmp(argv[1],"atomic",6))return atomic_fault(argv[1]);
    if (argc == 2) return !strcmp(argv[1],"pop-fault") ? pop_fault() :
        strstr(argv[1], "div") ? division(argv[1]) : repetition(argv[1]);
    uint64_t value = UINT64_MAX, flags;
    __asm__ volatile("addq $1,%0; pushfq; popq %1"
                     : "+r"(value), "=r"(flags) : : "cc");
    printf("add64 value=%016lx flags=%016lx mask=%016lx\n",
           (unsigned long)value, (unsigned long)(flags & 0x8d5), 0x8d5UL);
    return 0;
}
