[package]
name = "paludarium"
description = "x86-64 Linux user-mode emulator (library and command)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
paludarium-types.workspace = true
paludarium-host.workspace = true
paludarium-runtime.workspace = true
paludarium-loader.workspace = true

[lints]
workspace = true
